// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_2EAK-2L0odFVuGL1aqQh_cmhfxL6XY',
    appId: '1:467846370473:web:5ac63d1fffea483466c5b8',
    messagingSenderId: '467846370473',
    projectId: 'ss-final-project-fbefe',
    authDomain: 'ss-final-project-fbefe.firebaseapp.com',
    storageBucket: 'ss-final-project-fbefe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU7BkySMheN_Y0aGQba0KtcgfYmL0HDZo',
    appId: '1:467846370473:android:84d6de7deef0ba9066c5b8',
    messagingSenderId: '467846370473',
    projectId: 'ss-final-project-fbefe',
    storageBucket: 'ss-final-project-fbefe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMt-Av0nKCdmT67W_BklarmLqxyW1W6Og',
    appId: '1:467846370473:ios:cac8924cb72da9e066c5b8',
    messagingSenderId: '467846370473',
    projectId: 'ss-final-project-fbefe',
    storageBucket: 'ss-final-project-fbefe.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
